random_delays: True
segment_duration: 3000
#locomotion: ["walk", "jog" ]
modifiers: [ "none", "stealthily", "sportively" ]
transitions:
  - none:
      - orientation: 0
  - turn right:
      - orientation: 90
  - turn left:
      - orientation: -90
  - turn around:
      - orientation: 180
actions: [ "none", "jump", "pick-up something", "stretch your arms"]

sound_location: "resources/"